import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/layouts/header";
import { ClerkProvider } from "@clerk/nextjs";
import localFont from "next/font/local"


const raleway = localFont({
  src: "../../public/fonts/raleway.woff2",
  variable: "--font-raleway",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "E-commerce app",
  description: "E-commerce app, generated by Reza Tofighi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${raleway.variable}antialiased`}>
          <Header />
          <main>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
