import { ClerkProvider } from '@clerk/nextjs';
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "E-commerce app",
  description: "E-commerce app, generated by Reza Tofighi",
};
const StudioLayout = ({children}:{children:React.ReactNode}) => {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body>{children}</body>
      </html>
    </ClerkProvider>
  )
}

export default StudioLayout
